Repository f-lab-edu/YouAndMe, pull requests merged in 2021-11, with the labels that each got.

#114 Refactor Application DB Schema
  src/main/resources/schema-mysql.sql
  src/test/resources/sql/ddl.sql
Labels: 🛠REFACTOR

#115 ADD Readme, Refactor EmbeddedRedis
  src/main/java/com/yam/app/common/configuration/EmbeddedRedisConfiguration.java
  src/test/resources/application-test.yml
Labels: 📰DOCS, 🛠REFACTOR

#116 refactor paging query no offset
  src/main/java/com/yam/app/article/application/ArticleFacade.java
  src/main/java/com/yam/app/article/domain/ArticleReader.java
  src/main/java/com/yam/app/article/infrastructure/MybatisArticleRepository.java
  src/main/java/com/yam/app/article/presentation/ArticleQueryApi.java
  src/main/resources/mapper/xml/AccountQueryMapper.xml
  src/main/resources/mapper/xml/ArticleQueryMapper.xml
  src/main/resources/mapper/xml/MemberQueryMapper.xml
  src/test/java/com/yam/app/article/domain/FakeArticleRepository.java
  src/test/java/com/yam/app/article/infrastructure/ArticleReaderTest.java
Labels: 🛠REFACTOR, 🌱 Back
