Repository f-lab-edu/YouAndMe, pull requests merged in 2021-09, with the labels that each got.

#29 Use Case Common [Register] : Verify Email Token
  src/main/java/com/yam/app/account/application/AccountFacade.java
  src/main/java/com/yam/app/account/application/AccountTranslator.java
  src/main/java/com/yam/app/account/application/ConfirmRegisterAccountCommand.java
  src/main/java/com/yam/app/account/domain/AccountRepository.java
  src/main/java/com/yam/app/account/domain/ConfirmRegisterAccountProcessor.java
  src/main/java/com/yam/app/account/domain/TokenVerifier.java
  src/main/java/com/yam/app/account/infrastructure/AppConfiguration.java
  src/main/java/com/yam/app/account/infrastructure/MybatisAccountRepository.java
  src/main/java/com/yam/app/account/presentation/AccountCommandApi.java
  src/main/java/com/yam/app/account/presentation/ConfirmRegisterAccountRequest.java
  src/main/java/com/yam/app/account/presentation/RegisterAccountApi.java
  src/main/resources/mapper/xml/AccountCommandMapper.xml
  src/test/java/com/yam/app/account/domain/ConfirmRegisterAccountProcessorTest.java
  src/test/java/com/yam/app/account/domain/FakeAccountRepository.java
  src/test/java/com/yam/app/account/domain/RegisterAccountProcessorTest.java
  src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
  src/test/java/com/yam/app/account/infrastructure/MybatisAccountRepositoryTest.java
  src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
  src/test/java/com/yam/app/account/presentation/RegisterAccountApiTests.java
Labels: 🏗️ADD, 🌱 Back

#30 Refactor code
  src/main/java/com/yam/app/account/application/ConfirmRegisterAccountCommand.java
  src/main/java/com/yam/app/account/domain/AccountReader.java
  src/main/java/com/yam/app/account/domain/AccountRepository.java
  src/main/java/com/yam/app/account/domain/ConfirmRegisterAccountProcessor.java
  src/main/java/com/yam/app/account/domain/RegisterAccountProcessor.java
  src/main/java/com/yam/app/account/domain/TokenVerifier.java
  src/main/java/com/yam/app/account/infrastructure/AppConfiguration.java
  src/main/java/com/yam/app/account/infrastructure/MailManager.java
  src/main/java/com/yam/app/account/infrastructure/MybatisAccountRepository.java
  src/main/resources/mapper/xml/AccountCommandMapper.xml
  src/main/resources/mapper/xml/AccountReaderMapper.xml
  src/test/java/com/yam/app/account/domain/ConfirmRegisterAccountProcessorTest.java
  src/test/java/com/yam/app/account/domain/FakeAccountRepository.java
  src/test/java/com/yam/app/account/domain/PasswordEncrypterTest.java
  src/test/java/com/yam/app/account/domain/RegisterAccountProcessorTest.java
  src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
  src/test/java/com/yam/app/account/infrastructure/MybatisAccountRepositoryTest.java
  src/test/java/com/yam/app/account/integration/DummyMailDispatcher.java
  src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
Labels: 🛠REFACTOR, 🌱 Back

#31 Add permissions for each account
  src/main/java/com/yam/app/account/domain/Account.java
  src/main/java/com/yam/app/account/domain/Role.java
  src/main/java/com/yam/app/account/infrastructure/RoleTypeHandler.java
  src/main/java/com/yam/app/account/presentation/AccountCommandApi.java
  src/main/resources/mapper/xml/AccountCommandMapper.xml
  src/main/resources/sql/ddl.sql
  src/test/java/com/yam/app/account/infrastructure/MybatisAccountRepositoryTest.java
  src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
Labels: 🏗️ADD, 🌱 Back

#37 Add settings to enable logging services
  .gitignore
  build.gradle
  src/main/resources/log4j2.xml
Labels: 🌱 Back, 🐧 Infra

#40 Refactor code
  src/main/java/com/yam/app/account/application/AccountFacade.java
  src/main/java/com/yam/app/account/infrastructure/AccountPrincipal.java
  src/main/java/com/yam/app/account/infrastructure/AppConfiguration.java
  src/main/java/com/yam/app/account/infrastructure/LoginSessionUtils.java
  src/main/java/com/yam/app/account/infrastructure/SessionBasedLoginAccountProcessor.java
  src/main/java/com/yam/app/account/infrastructure/SessionManager.java
  src/main/java/com/yam/app/account/presentation/AccountCommandApi.java
  src/main/java/com/yam/app/account/presentation/AccountQueryApi.java
  src/main/java/com/yam/app/account/presentation/ConfirmRegisterAccountCommand.java
  src/main/java/com/yam/app/account/presentation/LoginAccountCommand.java
  src/main/java/com/yam/app/account/presentation/LoginAccountMethodArgumentResolver.java
  src/main/java/com/yam/app/account/presentation/RegisterAccountCommand.java
  src/main/java/com/yam/app/account/presentation/WebConfiguration.java
  src/test/java/com/yam/app/ArchUnitTests.java
  src/test/java/com/yam/app/account/domain/ConfirmRegisterAccountProcessorTest.java
  src/test/java/com/yam/app/account/domain/PasswordEncrypterStub.java
  src/test/java/com/yam/app/account/infrastructure/SessionBasedLoginAccountProcessorTest.java
  src/test/java/com/yam/app/account/integration/AccountIntegrationTests.java
  src/test/java/com/yam/app/account/presentation/AccountApiUri.java
  src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
  src/test/java/com/yam/app/account/presentation/AccountQueryApiTest.java
Labels: 🏗️ADD, 🛠REFACTOR, 🌱 Back

#45 It manages the storage and inquiry of sessions using an external session repository.
  build.gradle
  src/main/java/com/yam/app/common/configuration/EmbeddedRedisConfiguration.java
  src/main/java/com/yam/app/common/configuration/RedisConfiguration.java
  src/main/resources/application.yml
  src/test/java/com/yam/app/account/integration/AccountIntegrationTests.java
Labels: 🏗️ADD, 🌱 Back, 🐧 Infra

#47 Refactor code
  src/main/java/com/yam/app/account/application/AccountFacade.java
  src/main/java/com/yam/app/account/application/AccountTranslator.java
  src/main/java/com/yam/app/account/domain/Account.java
  src/main/java/com/yam/app/account/domain/AccountReader.java
  src/main/java/com/yam/app/account/domain/RegisterAccountProcessor.java
  src/main/java/com/yam/app/account/infrastructure/MailManager.java
  src/main/java/com/yam/app/account/infrastructure/MybatisAccountRepository.java
  src/main/java/com/yam/app/account/presentation/AccountResponse.java
  src/main/java/com/yam/app/account/presentation/RegisterAccountCommand.java
  src/main/resources/mapper/xml/AccountCommandMapper.xml
  src/main/resources/sql/ddl.sql
  src/main/resources/templates/mail/check-token.html
  src/test/java/com/yam/app/account/domain/ConfirmRegisterAccountProcessorTest.java
  src/test/java/com/yam/app/account/domain/FakeAccountRepository.java
  src/test/java/com/yam/app/account/domain/RegisterAccountProcessorTest.java
  src/test/java/com/yam/app/account/domain/TokenVerifierTest.java
  src/test/java/com/yam/app/account/infrastructure/SessionBasedLoginAccountProcessorTest.java
  src/test/java/com/yam/app/account/integration/AccountIntegrationTests.java
  src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
Labels: 🛠REFACTOR, 🌱 Back, ⏰Priority

#56 Add member db schema
  src/main/java/com/yam/app/account/domain/Account.java
  src/main/java/com/yam/app/common/configuration/DatabaseConfiguration.java
  src/main/java/com/yam/app/member/application/empty.txt
  src/main/java/com/yam/app/member/domain/empty.txt
  src/main/java/com/yam/app/member/infrastructure/empty.txt
  src/main/java/com/yam/app/member/presentation/empty.txt
  src/main/resources/mapper/xml/AccountQueryMapper.xml
  src/main/resources/sql/ddl.sql
  src/main/resources/sql/dml.sql
  src/test/java/com/yam/app/account/domain/RegisterAccountProcessorTest.java
Labels: 🏗️ADD, 🌱 Back

#57 Refactor code
  src/main/java/com/yam/app/account/application/AccountFacade.java
  src/main/java/com/yam/app/account/domain/RegisterAccountProcessor.java
  src/main/java/com/yam/app/account/infrastructure/AccountModuleConfiguration.java
  src/main/java/com/yam/app/account/infrastructure/MailManager.java
Labels: 🛠REFACTOR, 🌱 Back

#59 Refactor code
  src/main/java/com/yam/app/account/infrastructure/LoginAccountMethodArgumentResolver.java
  src/main/java/com/yam/app/account/infrastructure/SessionManager.java
  src/test/java/com/yam/app/account/infrastructure/SessionBasedLoginAccountProcessorTest.java
  src/test/java/com/yam/app/account/integration/AccountIntegrationTests.java
  src/test/java/com/yam/app/account/presentation/AccountCommandApiTests.java
Labels: 🛠REFACTOR, 🌱 Back

#60 Using @Async annotation
  src/main/java/com/yam/app/account/infrastructure/MailManager.java
  src/main/java/com/yam/app/common/configuration/AsyncConfiguration.java
Labels: 🏗️ADD, 🌱 Back, 🐧 Infra

#61 Configures to add default member domain values only to email confirmed users.
  src/main/java/com/yam/app/account/application/AccountFacade.java
  src/main/java/com/yam/app/account/domain/Account.java
  src/main/java/com/yam/app/account/domain/GenerateMemberEvent.java
  src/main/java/com/yam/app/account/domain/RegisterAccountConfirmEvent.java
  src/main/java/com/yam/app/account/infrastructure/AccountEventListener.java
  src/main/java/com/yam/app/adapter/DomainEventTranslator.java
  src/main/java/com/yam/app/member/domain/GenerateMemberEvent.java
  src/main/java/com/yam/app/member/domain/Member.java
  src/main/java/com/yam/app/member/domain/MemberReader.java
  src/main/java/com/yam/app/member/domain/MemberRepository.java
  src/main/java/com/yam/app/member/domain/RegisterAccountConfirmEvent.java
  src/main/java/com/yam/app/member/domain/empty.txt
  src/main/java/com/yam/app/member/infrastructure/MemberEventListener.java
  src/main/java/com/yam/app/member/infrastructure/MemberModuleConfiguration.java
  src/main/java/com/yam/app/member/infrastructure/MybatisMemberRepository.java
  src/main/java/com/yam/app/member/infrastructure/empty.txt
  src/main/resources/mapper/xml/AccountCommandMapper.xml
  src/main/resources/mapper/xml/MemberCommandMapper.xml
  src/main/resources/mapper/xml/MemberQueryMapper.xml
  src/main/resources/sql/ddl.sql
  src/test/java/com/yam/app/ArchUnitTests.java
Labels: 🏗️ADD, 🌱 Back, 🐧 Infra

#76 Refactor code
  src/main/java/com/yam/app/account/infrastructure/AccountEventListener.java
  src/main/java/com/yam/app/adapter/DomainEventTranslator.java
  src/main/java/com/yam/app/member/infrastructure/MemberEventListener.java
Labels: 🏗️ADD, 🛠REFACTOR, 🌱 Back
